```{r load-pkgs, include = FALSE}
library(learnr)
library(glue)
library(shinyalert)
library(palmerpenguins)
library(tidyverse)
library(nycflights13)
library(rlang)
library(googledrive)

knitr::opts_chunk$set(echo = FALSE)
```

```{r no-nas, echo = FALSE}
penguins_no_nas <- penguins %>%
  drop_na()

midwest_no_nas <- midwest %>%
  drop_na()

flights_no_nas <- flights %>%
  drop_na()
```

```{r setup, include = FALSE}
drive_auth(path = "creds.apps.googleusercontent.com.json")
```


```{r assessment, echo = FALSE, context = "server"}

access_username <- function() {
  session <- getDefaultReactiveDomain()
  
  query <- shiny::parseQueryString(session$clientData$url_search)
  
  if (!base::is.null(query[["user_id"]])) {
    user_id <- shinysurveys:::base_extract_user_id(query)
  } else {
    user_id <- "NO_USERNAME"
  }
  
  return(user_id)
}

i <- round(runif(1, 0, 1000000))
write_csv(data.frame(1), file = glue("data_{i}.csv"))
x <- drive_upload(glue("data_{i}.csv"), 
                  path = as_id("1fUCk_FXTulZZ_TCvWfMR5oMxiz5Os0do"))

save_assessment <- function(username) {
  
  input <- getDefaultReactiveDomain()$input
  
  assess_response <- tibble::tibble(
    group = "tidy",
    username = username,
    nervous_pre = input[["nervous-pre"]] %||% NA_character_,
    nervous_post = input[["nervous-post"]] %||% NA_character_,
    q1 = input[["q1"]] %||% NA_real_,
    q2 = input[["q2"]] %||% NA_real_,
    q3 = input[["q3"]] %||% NA_real_,
    age = input[["age"]] %||% NA_real_,
    gender = input[["gender"]] %||% NA_character_,
    self_describe_gender = input[["self_describe_gender"]] %||% NA_character_,
    education_attained = input[["education_attained"]] %||% NA_character_,
    first_language = input[["first_language"]] %||% NA_character_,
    first_language_other = input[["first_language_other"]] %||% NA_character_,
    read_language = input[["read_language"]] %||% NA_character_,
    learned_r = input[["learned_r"]] %||% NA_character_,
    years_using_r = input[["years_using_r"]] %||% NA_character_,
    learned_programming_not_r = input[["learned_programming_not_r"]] %||% NA_character_,
    years_programming_not_r = input[["years_programming_not_r"]] %||% NA_character_,
    completed_data_analysis = input[["completed_data_analysis"]] %||% NA_character_
  )
  
  write_csv(assess_response, file = glue::glue("assessment_{username}.csv"))
  drive_update(x, media = glue::glue("assessment_{username}.csv"))
}

update_assessments <- function() {
  
  input <- getDefaultReactiveDomain()$input
  
  assessment_inputs <- shiny::reactive({
    list(input[["nervous-pre"]],
         input[["nervous-post"]],
         input[["q1"]],
         input[["q2"]],
         input[["q3"]],
         input[["age"]],
         input[["gender"]],
         input[["self_describe_gender"]],
         input[["education_attained"]],
         input[["first_language"]],
         input[["first_language_other"]],
         input[["read_language"]],
         input[["learned_r"]],
         input[["years_using_r"]],
         input[["learned_programming_not_r"]],
         input[["years_programming_not_r"]],
         input[["completed_data_analysis"]]
    )
  })
  
  shiny::observeEvent(assessment_inputs(), {
    user_id <- access_username()
    
    save_assessment(username = user_id)
  }, 
  ignoreInit = TRUE
  )
}


update_assessments()


observeEvent(input$complete_session, {
  user_id <- access_username()
  
  if (is.na(input$q1) && is.na(input$q2) && is.na(input$q3)) {
    showModal(
      modalDialog(
        "Before you finish, please return to the \"Assessment\" tab and complete the 3 question assessment",
        footer = modalButton("Ok"),
        easyClose = TRUE
      )
    ) 
  } else {
    showModal(
      modalDialog(title = "Congratulations, you finished the study!",
                  textInput("email", 
                            "If you would like to receive a $10 Amazon gift card, please provide your email.", 
                            placeholder = "email@example.com"),
                  footer = actionButton("save_email", "Save Email")
      )
    )
  } 
}, ignoreInit = TRUE)
observeEvent(input$save_email, {
  contact <- tibble::tibble(
    email = input$email
  )
  i <- round(runif(1, 0, 1000000))
  write_csv(contact, file = glue::glue("contact_{i}.csv"))
  drive_upload(media = glue::glue("contact_{i}.csv"),
               path = as_id("1fUCk_FXTulZZ_TCvWfMR5oMxiz5Os0do"),
               overwrite = TRUE)
  
  removeModal()
  showModal(modalDialog("Thank you for participating! Please close your browser window now.", footer = NULL))
})
```